// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr50SPwqim4xQ03nQ6xhX2GrSC8Nocriw',
    appId: '1:632510698282:web:3c4763277a8159af058453',
    messagingSenderId: '632510698282',
    projectId: 'mynotes-5afb9',
    authDomain: 'mynotes-5afb9.firebaseapp.com',
    storageBucket: 'mynotes-5afb9.firebasestorage.app',
    measurementId: 'G-GPFRD31VX0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbbHEFfEXwLrcFHoETJC6zd6NeWsMdqPQ',
    appId: '1:632510698282:android:896a14859e065f53058453',
    messagingSenderId: '632510698282',
    projectId: 'mynotes-5afb9',
    storageBucket: 'mynotes-5afb9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2-wacyFRYlxu_uObUTFAbzohN5vv90X0',
    appId: '1:632510698282:ios:cbe5336a4ceba48a058453',
    messagingSenderId: '632510698282',
    projectId: 'mynotes-5afb9',
    storageBucket: 'mynotes-5afb9.firebasestorage.app',
    iosBundleId: 'com.abdulrafay.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2-wacyFRYlxu_uObUTFAbzohN5vv90X0',
    appId: '1:632510698282:ios:cbe5336a4ceba48a058453',
    messagingSenderId: '632510698282',
    projectId: 'mynotes-5afb9',
    storageBucket: 'mynotes-5afb9.firebasestorage.app',
    iosBundleId: 'com.abdulrafay.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr50SPwqim4xQ03nQ6xhX2GrSC8Nocriw',
    appId: '1:632510698282:web:49025ced9822971b058453',
    messagingSenderId: '632510698282',
    projectId: 'mynotes-5afb9',
    authDomain: 'mynotes-5afb9.firebaseapp.com',
    storageBucket: 'mynotes-5afb9.firebasestorage.app',
    measurementId: 'G-RCKYNEPLYF',
  );
}
